### ISSUE TITLE
Better urls

### ISSUE THREAD

**Issue by bdvholmes** [twokul/ember-cli-bugsnag#10]
Route names instead of urls. Open questions: what happens if error is thrown mid transition?

**Comment by bdvholmes** [comment]
Error/
    Attempted to handle event `reloadRecord` on <client-portal@model:session::ember360:current> while in state root.loaded.updated.invalid. Called with function (t){h(e,t)}.

**Comment by bdvholmes** [comment]
SecurityError/
    SecurityError: DOM Exception 18

**Comment by twokul** [comment]
`ReferenceError /events/2/purchase` -> `Reference Error: Event (/events/2/purchase)`

**Comment by bdvholmes** [comment]
TypeError/
    Cannot read property 'start' of null
