### ISSUE TITLE
Uncaught TypeError: instance.lookup is not a function

### ISSUE THREAD

**Issue by twokul** [twokul/ember-cli-bugsnag#32]
https://github.com/twokul/ember-cli-bugsnag/blob/master/app/instance-initializers/bugsnag.js#L32

**Comment by twokul** [comment]
possibly just need to change it to

```javascript
instance.get('router');
```

**Comment by twokul** [comment]
cc @bdvholmes @mmun

**Comment by twokul** [comment]
Ember 1.13.13

**Comment by hjdivad** [comment]
@twokul seems like it's using an API introduced in 2.3.0

`instance.container.lookup` should also be fine for 1.13.x

unless you want to have a 1.13.x compat branch separate from a 2.x compat branch feature detection might be the way to go here

**Comment by hjdivad** [comment]
@twokul `instance.get('router')` seems to be private at least in 1.13.x

**Comment by bdvholmes** [comment]
@hjdivad we'll definitely be doing a minor release for the addon since it's a breaking change. E.g. version 0.2.0

**Comment by hjdivad** [comment]
@bdvholmes I believe this issue exists currently with what is effectively released, ie what you get if you run the [installation instructions](https://github.com/twokul/ember-cli-bugsnag#installation) on an app with ember 1.13.x.

**Comment by vivian-ho** [comment]
I'm trying to upgrade to Ember 2.5 from 2.0 and getting this:  TypeError: instance.container is not a function

Sample initializer:
App.initializer({
    name: 'appInitializers',
    initialize: function(app) {
      app.inject('controller', 'test', 'test:main');
      app.inject('component', 'test', 'test:main');
      app.inject('route', 'test', 'test:main');
      app.inject('adapter', 'test', 'test:main');
      app.inject('serializer', 'test', 'test:main');
    },
  });

wondering what I'm doing wrong.  Thanks for any help.
